name: CI Workflow

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js 20 environment
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      # Install dependencies
      - name: Install dependencies
        run: yarn install
